import Header from '@/src/components/Header/Header'
import MainContainer from '@/src/components/MainComtainer/MainContainer'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export interface ILayoutProps {
//   children: React.ReactNode
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
   
      <body className={inter.className}>
        <Header />
        <MainContainer>
        {children}</MainContainer></body>
    </html>
  )
}
